Avukat_2/Models/Avukat.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Avukat_2.Models
{
    public class Avukat
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int AvukatID { get; set; }
        public string AvukatAd { get; set; }
        public string AvukatSoyad { get; set; }
        public string telno { get; set; }
        public string mail { get; set; }




        public virtual List<Davalar> Davalars { get; set; }
        public virtual List<BitenDavalar> bDavalars { get; set; }
    }
}

Avukat_2/Controllers/AvukatsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Avukat_2.Models;
using Avukat_2.Security;

namespace Avukat_2.Controllers
{
    public class AvukatsController : Controller
    {
        private OurDbContext db = new OurDbContext();

        // GET: Avukats
        [CustomAuthorize(Roles = "superadmin")]
        public ActionResult Index()
        {
            return View(db.avukats.ToList());
        }

        // GET: Avukats/Details/5
        [CustomAuthorize(Roles = "superadmin")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Avukat avukat = db.avukats.Find(id);
            if (avukat == null)
            {
                return HttpNotFound();
            }
            return View(avukat);
        }

        // GET: Avukats/Create
        [CustomAuthorize(Roles = "superadmin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Avukats/Create
        // Aşırı gönderim saldırılarından korunmak için, lütfen bağlamak istediğiniz belirli özellikleri etkinleştirin, 
        // daha fazla bilgi için https://go.microsoft.com/fwlink/?LinkId=317598 sayfasına bakın.
        [HttpPost]
        [CustomAuthorize(Roles = "superadmin")]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "AvukatID,AvukatAd,AvukatSoyad,telno,mail")] Avukat avukat)
        {
            if (ModelState.IsValid)
            {
                db.avukats.Add(avukat);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(avukat);
        }

        // GET: Avukats/Edit/5
        [CustomAuthorize(Roles = "superadmin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Avukat avukat = db.avukats.Find(id);
            if (avukat == null)
            {
                return HttpNotFound();
            }
            return View(avukat);
        }

        // POST: Avukats/Edit/5
        // Aşırı gönderim saldırılarından korunmak için, lütfen bağlamak istediğiniz belirli özellikleri etkinleştirin, 
        // daha fazla bilgi için https://go.microsoft.com/fwlink/?LinkId=317598 sayfasına bakın.
        [HttpPost]
        [CustomAuthorize(Roles = "superadmin")]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "AvukatID,AvukatAd,AvukatSoyad,telno,mail")] Avukat avukat)
        {
            if (ModelState.IsValid)
            {
                db.Entry(avukat).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(avukat);
        }

        // GET: Avukats/Delete/5
        [CustomAuthorize(Roles = "superadmin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Avukat avukat = db.avukats.Find(id);
            if (avukat == null)
            {
                return HttpNotFound();
            }
            return View(avukat);
        }


        [CustomAuthorize(Roles = "superadmin")]
        // POST: Avukats/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Avukat avukat = db.avukats.Find(id);
            db.avukats.Remove(avukat);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Avukat_2/Controllers/DeleteController.cs
using Avukat_2.Models;
using Avukat_2.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Globalization;
using Avukat_2.Security;

namespace Avukat_2.Controllers
{
    public class DeleteController : Controller
    {
        OurDbContext db = new OurDbContext();

        [CustomAuthorize(Roles = "superadmin")]
        public ActionResult Davasil()
        {
            OurDbContext db = new OurDbContext();
            DavakayitViewModel dkb = new DavakayitViewModel();
            dkb.bitenDavalars = db.bitendavalars.ToList();
            dkb.davalars = db.davalars.ToList();
            dkb.avukats = db.avukats.ToList();

            return View(dkb);
        }

        [CustomAuthorize(Roles = "superadmin")]
        public ActionResult Musterisil()
        {
            OurDbContext db = new OurDbContext();
            MusteriListeleViewModel dkb = new MusteriListeleViewModel();
            dkb.bitenmusteriler = db.bitenmusterilers.ToList();
            dkb.musteriler = db.musterilers.ToList();
            return View(dkb);
        }

        public string davvasil(string ID)
        {
            string test = "/uploads/";
            try
            {
                int silinecekid = int.Parse(ID.Substring(2), CultureInfo.CurrentCulture);
                if (ID[0] == 'a')
                {
                    Davalar dv = db.davalars.Where(x => x.DavaId == silinecekid).FirstOrDefault();
                    if(dv.Musteriler.musteriSoyad != null)
                    {
                        test += "bireysel/";
                    }
                    else
                    {
                        test += "kurumsal/";
                    }
                    test += dv.Musteriler.musteriTc;
                    test += "/aktifdavalar/";
                    test += dv.DavaAdi;
                    System.IO.Directory.Delete(Server.MapPath(test), true);

                    db.davalars.Remove(dv);
                    db.SaveChanges();
                    return "success";
                }
                else if (ID[0] == 'b')
                {
                    BitenDavalar dvb = db.bitendavalars.Where(x => x.DavaId == silinecekid).FirstOrDefault();
                    if (dvb.Musteriler.musteriSoyad != null)
                    {
                        test += "bireysel/";
                    }
                    else
                    {
                        test += "kurumsal/";
                    }
                    if (dvb.Musteriler != null)
                    {
                        test += dvb.Musteriler.musteriTc;
                    }
                    else { test += dvb.BMusteriler.musteriTc; }
                    test += "/bitendavalar/";
                    test += dvb.DavaAdi;

                    Directory.Delete(Server.MapPath(test), true);
                    db.bitendavalars.Remove(dvb);
                    db.SaveChanges();
                    return "success";
                }
                else
                {
                    return "externalerror";
                }
            }
            catch (Exception)
            {
                return "error";
                throw;
            }
            
        }

        public string musteriyiSil(string ID)
        {
            string test = "/uploads/";
            try
            {
                int silinecekid = int.Parse(ID.Substring(2), CultureInfo.CurrentCulture);
                if (ID[0] == 'a')
                {
                    Musteriler mst = db.musterilers.Where(x => x.UserID == silinecekid).FirstOrDefault();
                   
                    if(mst.musteriSoyad != null)
                    {
                        test += "bireysel/";
                    }
                    else { test += "kurumsal/"; }
                    test += mst.musteriTc+"/";
                    Directory.Delete(Server.MapPath(test), true);

                    db.davalars.RemoveRange(mst.Davalars);
                    db.SaveChanges();

                    db.bitendavalars.RemoveRange(mst.BDavalars);
                    db.SaveChanges();

                    db.musterilers.Remove(mst);
                    db.SaveChanges();

                    return "success";
                }
                else if (ID[0] == 'b')
                {
                    BitenMusteriler bmst = db.bitenmusterilers.Where(x => x.UserID == silinecekid).FirstOrDefault();

                    if (bmst.musteriSoyad != null)
                    {
                        test += "bireysel/";
                    }
                    else { test += "kurumsal/"; }
                    test += bmst.musteriTc;
                    Directory.Delete(Server.MapPath(test), true);

                    db.bitendavalars.RemoveRange(bmst.BDavalars);
                    db.SaveChanges();

                    db.bitenmusterilers.Remove(bmst);
                    db.SaveChanges() ;
                    return "success";
                }
                else
                {
                    return "externalerror";
                }
            }
            catch (Exception e)
            {
                return "error";
                throw;
            }

        }

    }
}

Avukat_2/Views/Avukats/Delete.cshtml
@model Avukat_2.Models.Avukat
@using Avukat_2.Security;
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
   
</body>
</html>


<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Gentelella Alela! | </title>
    <!-- Bootstrap -->
    <link href="~/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="~/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <!-- NProgress -->
    <link href="~/vendors/nprogress/nprogress.css" rel="stylesheet">
    <!-- jQuery custom content scroller -->
    <link href="~/vendors/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.min.css" rel="stylesheet" />
    <!-- Custom Theme Style -->
    <link href="~/build/css/custom.min.css" rel="stylesheet">
</head>
<body class="nav-md">
    <div class="container body">
        <div class="main_container">
            <div class="col-md-3 left_col">
                <div class="left_col scroll-view">
                    <div class="navbar nav_title" style="border: 0;">
                        <a class="site_title"><i class="fa fa-legal"></i> <span>Sakarya Büroosu</span></a>
                    </div>
                    <div class="clearfix"></div>
                    <!-- menu profile quick info -->
                    <div class="profile clearfix">
                        <div class="profile_pic">
                            <img src="images/img.jpg" alt="..." class="img-circle profile_img">
                        </div>
                        <div class="profile_info">
                            <span>Hoşgeldin,</span>
                            <h2>@SessionPersister.Username  @Session["modtype"]</h2>
                        </div>
                    </div>
                    <!-- /menu profile quick info -->
                    <br />
                    <!-- sidebar menu -->
                    <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
                        <div class="menu_section">
                            <h3>General</h3>
                            <ul class="nav side-menu">

                                @{

                                    if (Session["modtype"] != null)
                                    {
                                        if (Session["modtype"].ToString() == "Yönetici")
                                        {
                                            <li>
                                                <a href="@Url.Action("panel", "Admin")"><i class="fa fa-dashboard"></i>Yönetim Paneli</a>
                                            </li>
                                        }
                                    }

                                }
                                <li>
                                    <a><i class="fa fa-users"></i> Müşteriler <span class="fa fa-chevron-down"></span></a>
                                    <ul class="nav child_menu">
                                        <li><a href="@Url.Action("bireyselmusteriler", "Admin")">Bireysel Müşterileri Listele/Düzenle</a></li>
                                        <li><a href="@Url.Action("kurumsalmusteriler", "Admin")">Kurumsal Müşterileri Listele/Düzenle</a></li>
                                    </ul>
                                </li>
                                <li>
                                    <a><i class="fa fa-briefcase"></i> Davalar <span class="fa fa-chevron-down"></span></a>
                                    <ul class="nav child_menu">
                                        <li><a href="@Url.Action("davakayit", "Admin")">Dava Ekle</a></li>
                                        <li><a href="@Url.Action("davakapat", "Admin")">Dava Kapat</a></li>
                                        <li><a href="@Url.Action("bireyseldavalar", "Admin")">Bireysel Davaları Listele/Düzenle</a></li>
                                        <li><a href="@Url.Action("kurumsaldavalar", "Admin")">Kurumsal Davaları Listele/Düzenle</a></li>
                                    </ul>
                                </li>
                                @{
                                    if (Session["modtype"] != null)
                                    {
                                        if (Session["modtype"].ToString() == "Yönetici")
                                        {
                                            <li>
                                                <a><i class="fa fa-database"></i> Silme İşlemleri <span class="fa fa-chevron-down"></span></a>
                                                <ul class="nav child_menu">
                                                    <li><a href="@Url.Action("Davasil", "Delete")">Dava Sil</a></li>
                                                    <li><a href="@Url.Action("Musterisil", "Delete")">Müşteri Sil</a></li>
                                                </ul>
                                            </li>
                                        }
                                    }
                                }
                                @{
                                    if (Session["modtype"] != null)
                                    {
                                        if (Session["modtype"].ToString() == "Yönetici")
                                        {
                                            <li>
                                                <a><i class="fa fa-desktop"></i> Yardımcılar <span class="fa fa-chevron-down"></span></a>
                                                <ul class="nav child_menu">
                                                    <li><a href="@Url.Action("Create", "superadmin")">Yardımcı Ekle</a></li>
                                                    <li><a href="@Url.Action("Index", "superadmin")">Yardımcıları Listele / Düzenle</a></li>
                                                </ul>
                                            </li>
                                        }
                                    }
                                }
                                @{
                                    if (Session["modtype"] != null)
                                    {
                                        if (Session["modtype"].ToString() == "Yönetici")
                                        {

                                            <li>
                                                <a><i class="fa fa-legal"></i> Avukatlar <span class="fa fa-chevron-down"></span></a>
                                                <ul class="nav child_menu">
                                                    <li><a href="@Url.Action("Create", "Avukats")">Avukat Ekle</a></li>
                                                    <li><a href="@Url.Action("Index", "Avukats")">Avukatları Listele / Düzenle</a></li>
                                                </ul>
                                            </li>
                                        }
                                    }
                                }



                                <li><a href="javascript:void(0)"><i class="fa fa-laptop"></i> Landing Page <span class="label label-success pull-right">Coming Soon</span></a></li>
                            </ul>
                        </div>
                    </div>
                    <!-- /sidebar menu -->
                    <!-- /menu footer buttons -->
                    <div class="sidebar-footer hidden-small">
                        <a data-toggle="tooltip" data-placement="top" title="Settings">
                            <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
                        </a>
                        <a data-toggle="tooltip" data-placement="top" title="FullScreen">
                            <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
                        </a>
                        <a data-toggle="tooltip" data-placement="top" title="Lock">
                            <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
                        </a>
                        <a data-toggle="tooltip" data-placement="top" title="Logout" href="@Url.Action("Logout", "Admin")">
                            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
                        </a>
                    </div>
                    <!-- /menu footer buttons -->
                </div>
            </div>
            <div class="top_nav">
                <div class="nav_menu">
                    <nav>
                        <div class="nav toggle">
                            <a id="menu_toggle"><i class="fa fa-bars"></i></a>
                        </div>
                        <ul class="nav navbar-nav navbar-right">
                            <li class="">
                                <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                    <img src="images/img.jpg" alt="">@SessionPersister.Username
                                    <span class=" fa fa-angle-down"></span>
                                </a>
                                <ul class="dropdown-menu dropdown-usermenu pull-right">
                                    <li><a href="javascript:;"> Profile</a></li>
                                    <li>
                                        <a href="javascript:;">
                                            <span class="badge bg-red pull-right">50%</span>
                                            <span>Settings</span>
                                        </a>
                                    </li>
                                    <li><a href="javascript:;">Help</a></li>
                                    <li><a href="@Url.Action("Logout", "Admin")"><i class="fa fa-sign-out pull-right"></i> Log Out</a></li>
                                </ul>
                            </li>
                           
                        </ul>
                    </nav>
                </div>
            </div>
            <!-- /top navigation -->
            <!-- page content -->
            <div class="right_col" role="main">
                <h3>Are you sure you want to delete this?</h3>
                <div>
                    <h4>Avukat</h4>
                    <hr />
                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.AvukatAd)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.AvukatAd)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.AvukatSoyad)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.AvukatSoyad)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.telno)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.telno)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.mail)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.mail)
                        </dd>

                    </dl>

                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-actions no-color">
                            <input type="submit" value="Delete" class="btn btn-default" /> |
                            @Html.ActionLink("Back to List", "Index")
                        </div>
                    }
                </div>
            </div>
            <!-- /page content -->
            <!-- Footer -->
            <footer id="footer" class="footer pb-0 bg-deep">

                <div class="mu-footer-bottom">
                    <div class="container">
                        <div class="mu-footer-bottom-area" style="text-align:center;">
                            <p>© Tüm Hakları Saklıdır. Designed by <a href="https://www.hasturkyazilim.com/" rel="nofollow" style="color:#c99809;">HASTÜRK YAZILIM</a></p>
                        </div>
                    </div>
                </div>
            </footer>
            <!-- /footer content -->
        </div>
    </div>
    <!-- jQuery -->
    <script src="~/vendors/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap -->
    <script src="~/vendors/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- FastClick -->
    <script src="~/vendors/fastclick/lib/fastclick.js"></script>
    <!-- NProgress -->
    <script src="~/vendors/nprogress/nprogress.js"></script>
    <!-- jQuery custom content scroller -->
    <script src="~/vendors/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js"></script>
    <!-- Custom Theme Scripts -->
    <script src="~/build/js/custom.min.js"></script>
</body>
</html>